export const ALL_FORMATS = [
	'Vinyl',
	'CD',
	'Cassette',
	'CDr',
	'Flexi-disc',
	'Shellac',
	'Lathe Cut',
	'Vinyl Disc',
	'Acetate',
	'Card Backed Picture Sleeve',
	'Vinyl 7"',
	'Vinyl 10"',
	'Vinyl 12"',
	'Vinyl 14"',
	'Vinyl 8"',
	'Vinyl Reel-To-Reel',
	'Vinyl 5"',
	'Vinyl 16"',
	'Vinyl 9"',
	'Vinyl 3"',
	'Vinyl 6"',
	'Vinyl 78 RPM',
	'Vinyl 80 RPM',
	'Vinyl 33⅓ RPM',
	'Vinyl 45 RPM'
];
